'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'en' | 'zh';

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.opportunities': 'Opportunities',
    'nav.sell': 'Intent Registry',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Log in',
    'nav.getStarted': 'Get Started',
    'nav.investorLogin': 'Investor Login',
    'nav.faLogin': 'FA/Admin Login',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    
    // Hero
    'hero.badge': 'ByteDance Officially Authorized Platform',
    'hero.title1': 'ByteDance Equity',
    'hero.title2': 'Secondary Market',
    'hero.description': "The world's first officially authorized equity trading platform for ByteDance. Complete KYC, equity management, and escrow services for family offices and institutional investors.",
    'hero.startKYC': 'Start KYC Verification',
    'hero.browse': 'Browse Opportunities',
    
    // Stats
    'stat.valuation': 'Implied Valuation',
    'stat.volume': 'Monthly Volume',
    'stat.discount': 'Avg Discount',
    'stat.buyers': 'Active Buyers',
    
    // Features
    'features.title': 'Why Choose VentureFlow?',
    'features.description': 'One-stop ByteDance equity trading service, from KYC verification to closing, with professional support throughout.',
    'features.kyc.title': 'KYC Verification',
    'features.kyc.desc': 'HKMA-compliant institutional verification process ensuring regulatory compliance.',
    'features.equity.title': 'Equity Management',
    'features.equity.desc': 'Carta-inspired equity management tools to track your portfolio performance in real-time.',
    'features.deal.title': 'Deal Execution',
    'features.deal.desc': 'Exclusive deal rooms and HK bank escrow accounts ensuring transaction security.',
    'features.compliance.title': 'Compliance',
    'features.compliance.desc': 'ByteDance official authorization with legal witness and full legal protection.',
    
    // Opportunities
    'opp.title': 'Featured Opportunities',
    'opp.description': 'Curated ByteDance equity deals with verified valuations',
    'opp.viewAll': 'View All',
    'opp.page.title': 'Investment Opportunities',
    'opp.page.description': 'Browse verified companies and explore exclusive equity deals in ByteDance and other pre-IPO unicorns.',
    'opp.page.sellShares': '💼 Sell Your Shares',
    'opp.page.totalCompanies': 'Total Companies',
    'opp.page.activeListings': 'Active Listings',
    'opp.page.totalValuation': 'Total Valuation',
    'opp.page.companyDetail': 'Company Detail',
    'opp.page.inquireNow': '💰 Inquire Now',
    'opp.page.noDeals': 'No active deals available at the moment.',
    'opp.page.contactFA': 'Contact our FA team for more opportunities.',
    'opp.page.backToList': '← Back to Opportunities',
    'opp.page.shareOpportunity': '📤 Share Opportunity',
    'opp.page.learnMore': 'Learn More',
    
    // Testimonials
    'testimonials.title': 'Trusted by Investors',
    'testimonials.description': 'Over 500 institutions and family offices completed their ByteDance equity allocation through our platform',
    'testimonials.verified': 'Verified Investor',
    
    // CTA
    'cta.title': 'Start Your Equity Investment Journey',
    'cta.description': "Whether you're looking for early institutional blocks or employee option transfers, our professional team provides end-to-end support.",
    'cta.browse': 'Browse Opportunities',
    'cta.contact': 'Contact Advisor',
    
    // Footer
    'footer.platform': 'Platform',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.rights': '© 2026 VentureFlow. All rights reserved.',
    
    // About Page
    'about.title': 'About VentureFlow',
    'about.subtitle': "The world's first officially authorized ByteDance equity secondary market trading platform",
    'about.mission': 'Our Mission',
    'about.missionText1': 'To provide a transparent, compliant, and efficient platform for ByteDance equity trading, connecting institutional investors with high-quality investment opportunities.',
    'about.missionText2': "We bridge the gap between private company shareholders and qualified investors, ensuring fair pricing, regulatory compliance, and seamless transaction execution.",
    'about.missionText3': 'Our platform combines cutting-edge technology with deep industry expertise to deliver the best secondary market experience.',
    'about.milestones': 'Key Milestones',
    'about.stats.founded': 'Founded',
    'about.stats.team': 'Team Size',
    'about.stats.licensed': 'Licensed In',
    'about.stats.transactions': 'Transactions',
    'about.values.title': 'Our Values',
    'about.values.desc': 'The principles that guide everything we do',
    'about.values.compliance': 'Compliance First',
    'about.values.transparency': 'Transparency',
    'about.values.efficiency': 'Efficiency',
    'about.team.title': 'Leadership Team',
    'about.team.desc': 'Industry veterans with decades of combined experience',
    'about.partners.title': 'Trusted Partners',
    'about.partners.desc': 'Working with leading institutions to deliver excellence',
    'about.cta.title': 'Join the Future of Equity Trading',
    'about.cta.desc': 'Start your investment journey with the most trusted ByteDance equity platform',
    'about.cta.start': 'Get Started Now',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team of experts',
    'contact.email': 'Email',
    'contact.hq': 'Headquarters',
    'contact.phone': 'Phone',
    'contact.wechat': 'WeChat',
    'contact.messageTitle': 'Send us a Message',
    'contact.sent': 'Message Sent!',
    'contact.sentDesc': 'Thank you for contacting us. Our team will respond within 24 hours.',
    'contact.sendAnother': 'Send another message',
    'contact.name': 'Full Name',
    'contact.emailLabel': 'Email Address',
    'contact.company': 'Company',
    'contact.subject': 'Subject',
    'contact.selectSubject': 'Select a subject',
    'contact.subject.investment': 'Investment Inquiry',
    'contact.subject.selling': 'Selling Shares',
    'contact.subject.partnership': 'Partnership Opportunity',
    'contact.subject.support': 'Technical Support',
    'contact.subject.other': 'Other',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.officeHours': 'Office Hours',
    'contact.weekdays': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.hours': '9:00 AM - 6:00 PM HKT',
    'contact.appointment': 'By Appointment',
    'contact.closed': 'Closed',
    'contact.departments': 'Departments',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.desc': 'Quick answers to common questions',
    
    // KYC Page
    'kyc.title': 'KYC Verification',
    'kyc.subtitle': 'Complete investor verification to unlock investment opportunities',
    'kyc.step1': 'Account Type',
    'kyc.step2': 'Basic Information',
    'kyc.step3': 'Identity Information',
    'kyc.step4': 'Investor Qualification',
    'kyc.step5': 'Risk Disclosure',
    'kyc.individual': 'Individual Investor',
    'kyc.institutional': 'Institutional Investor',
    'kyc.fullName': 'Full Name',
    'kyc.email': 'Email',
    'kyc.phone': 'Phone',
    'kyc.passport': 'Passport/ID Number',
    'kyc.investorCert': 'Accredited Investor Certificate',
    'kyc.riskDisclosure': 'Risk Disclosure',
    'kyc.submit': 'Submit Verification',
    'kyc.success': 'Verification Submitted!',
    'kyc.successDesc': 'Your KYC application has been submitted. We will review within 24 hours.',
    
    // Sell Page
    'sell.title': 'Sell Shares',
    'sell.subtitle': 'List your shares for sale. Our professional team will provide the best pricing.',
    'sell.step1': 'Asset Information',
    'sell.step2': 'Seller Information',
    'sell.step3': 'Documents',
    'sell.step4': 'Additional Info',
    'sell.companyName': 'Company Name',
    'sell.shareType': 'Share Type',
    'sell.shareCount': 'Number of Shares',
    'sell.estimatedValue': 'Estimated Value',
    'sell.sellerType': 'Seller Type',
    'sell.contactName': 'Contact Name',
    'sell.documents': 'Documents',
    'sell.proofOfOwnership': 'Proof of Ownership',
    'sell.purchaseAgreement': 'Purchase Agreement',
    'sell.idVerification': 'ID Verification',
    'sell.reasonForSelling': 'Reason for Selling',
    'sell.minimumPrice': 'Minimum Price',
    'sell.urgency': 'Urgency',
    'sell.submit': 'Submit Listing',
    'sell.success': 'Listing Submitted!',
    'sell.successDesc': 'Our FA team will contact you within 2 hours with market valuation and trading advice.',
    
    // Company Detail Page
    'company.detail': 'Company Detail',
    'company.inquireNow': '💰 Inquire Now',
    'company.noDeals': 'No active deals available at the moment.',
    'company.contactFA': 'Contact our FA team for more opportunities.',
    'company.backToList': '← Back to Opportunities',
    'company.shareOpportunity': '📤 Share Opportunity',
    'company.learnMore': 'Learn More',
    'company.valuation': 'Valuation',
    'company.pricePerShare': 'Price/Share',
    'company.volume': 'Volume',
    'company.discount': 'Discount',
    'company.founded': 'Founded',
    'company.headquarters': 'Headquarters',
    'company.industry': 'Industry',
    'company.description': 'Description',
    'company.activeDeals': 'Active Deals',
    'company.expressInterest': 'Express Interest',
    
    // Login Pages
    'login.title': 'FA Backend Management',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.demoCredentials': 'Demo Credentials:',
    'login.investorLink': '👤 Investor Login →',
    
    'userLogin.title': 'Investor Login',
    'userLogin.subtitle': 'Access your portfolio and investment opportunities',
    'userLogin.emailLabel': 'Email Address',
    'userLogin.passwordLabel': 'Password',
    'userLogin.signIn': 'Sign In',
    'userLogin.signingIn': 'Signing in...',
    'userLogin.kycLink': 'Complete KYC to Register',
    'userLogin.faLoginLink': 'FA/Admin Login →',
    'userLogin.demoNote': 'Demo: Any email / Any password',
    
    // FA Dashboard
    'faDash.title': 'Dashboard',
    'faDash.totalGmv': 'Total GMV',
    'faDash.pendingBuyers': 'Pending Buyers',
    'faDash.activeDeals': 'Active Deals',
    'faDash.monthlyClosed': 'Monthly Closed',
    'faDash.recentActivity': 'Recent Activity',
    'faDash.quickActions': 'Quick Actions',
    'faDash.marketOverview': 'Market Overview',
    'faDash.reviewKYC': 'Review KYC',
    'faDash.createAsset': 'Create Asset',
    'faDash.manageDeals': 'Manage Deals',
    'faDash.aiTools': 'AI Tools',
    
    // Buyers Page
    'buyers.title': 'Buyer Management',
    'buyers.search': 'Search buyers...',
    'buyers.addBuyer': 'Add Buyer',
    'buyers.buyer': 'Buyer',
    'buyers.email': 'Email',
    'buyers.type': 'Type',
    'buyers.kycStatus': 'KYC Status',
    'buyers.inquiries': 'Inquiries',
    'buyers.lastContact': 'Last Contact',
    'buyers.actions': 'Actions',
    'buyers.viewDetails': 'View Details',
    'buyers.approveKYC': 'Approve KYC',
    'buyers.rejectKYC': 'Reject KYC',
    'buyers.addFollowUp': 'Add Follow-up',
    'buyers.sendEmail': 'Send Email',
    'buyers.scheduleMeeting': 'Schedule Meeting',
    'buyers.aiGenerate': '✨ AI Generate',
    
    // Orders Page
    'orders.title': 'Order Management',
    'orders.createOrder': 'Create Order',
    'orders.orderId': 'Order ID',
    'orders.asset': 'Asset',
    'orders.buyer': 'Buyer',
    'orders.amount': 'Amount',
    'orders.status': 'Status',
    'orders.created': 'Created',
    'orders.view': 'View',
    'orders.updateStatus': 'Update Status',
    
    // Assets Page
    'assets.title': 'Asset Management',
    'assets.createAsset': 'Create Asset',
    'assets.assetName': 'Asset Name',
    'assets.valuation': 'Valuation',
    'assets.priceShare': 'Price/Share',
    'assets.volume': 'Volume',
    'assets.discount': 'Discount',
    'assets.status': 'Status',
    'assets.edit': 'Edit',
    'assets.deactivate': 'Deactivate',
    
    // Deals Page
    'deals.title': 'Deal Pipeline',
    'deals.newDeal': 'New Deal',
    'deals.dealName': 'Deal Name',
    'deals.value': 'Value',
    'deals.stage': 'Stage',
    'deals.lead': 'Lead',
    'deals.probability': 'Probability',
    'deals.moveForward': 'Move Forward',
    'deals.moveBack': 'Move Back',
    
    // Agreements Page
    'agreements.title': 'Agreement Management',
    'agreements.newAgreement': 'New Agreement',
    'agreements.agreementName': 'Agreement Name',
    'agreements.type': 'Type',
    'agreements.party': 'Party',
    'agreements.status': 'Status',
    'agreements.signed': 'Signed',
    'agreements.pending': 'Pending',
    'agreements.draft': 'Draft',
    'agreements.download': 'Download',
    'agreements.send': 'Send',
    
    // Commission Page
    'commission.title': 'Commission Tracking',
    'commission.dealId': 'Deal ID',
    'commission.amount': 'Amount',
    'commission.rate': 'Rate',
    'commission.commission': 'Commission',
    'commission.dueDate': 'Due Date',
    'commission.export': 'Export Report',
    
    // AI Tools Page
    'aiTools.title': 'AI Analysis Center',
    'aiTools.emailGen': 'Email Generator',
    'aiTools.buyerAnalysis': 'Buyer Analysis',
    'aiTools.smartMatch': 'Smart Match',
    'aiTools.scheduleAssistant': 'Schedule Assistant',
    'aiTools.generateEmail': 'Generate Email',
    'aiTools.analyzeBuyer': 'Analyze Buyer',
    'aiTools.findMatches': 'Find Matches',
    'aiTools.scheduleMeeting': 'Schedule Meeting',
    
    // Settings Page
    'settings.title': 'Settings',
    'settings.profile': 'Profile Settings',
    'settings.notifications': 'Notification Settings',
    'settings.team': 'Team Management',
    'settings.apiKeys': 'API Keys',
    'settings.save': 'Save Changes',
    'settings.logout': 'Logout',
    
    // User Dashboard
    'userDash.title': 'My Portfolio',
    'userDash.totalValue': 'Total Portfolio Value',
    'userDash.totalGainLoss': 'Total Gain/Loss',
    'userDash.activeInquiries': 'Active Inquiries',
    'userDash.myHoldings': 'My Holdings',
    'userDash.shares': 'shares',
    'userDash.avgPrice': 'Avg Price',
    'userDash.currentPrice': 'Current Price',
    'userDash.refValuation': 'Reference Valuation',
    'userDash.requestSell': 'Request to Sell',
    'userDash.details': 'Details',
    'userDash.myInquiries': 'My Inquiries',
    'userDash.newInquiry': '+ New Inquiry',
    'userDash.quickActions': 'Quick Actions',
    'userDash.browseOpp': 'Browse Opportunities',
    'userDash.sellShares': 'Sell My Shares',
    'userDash.sellRequestTitle': 'Request to Sell',
    'userDash.sharesCount': 'Shares',
    'userDash.estValue': 'Estimated Value',
    'userDash.faContact': 'An FA representative will contact you within 24 hours.',
    'userDash.cancel': 'Cancel',
    'userDash.submitRequest': 'Submit Request',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.opportunities': '投资机会',
    'nav.sell': '意向登记',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.login': '登录',
    'nav.getStarted': '开始使用',
    'nav.investorLogin': '投资者登录',
    'nav.faLogin': 'FA/管理员登录',
    'nav.dashboard': '仪表板',
    'nav.logout': '退出',
    
    // Hero
    'hero.badge': '字节跳动官方授权平台',
    'hero.title1': '字节跳动股权',
    'hero.title2': '二级市场',
    'hero.description': '全球首个字节跳动官方授权股权交易平台。为家族办公室和机构投资者提供完整的 KYC、股权管理和托管服务。',
    'hero.startKYC': '开始 KYC 认证',
    'hero.browse': '浏览投资机会',
    
    // Stats
    'stat.valuation': '隐含估值',
    'stat.volume': '月交易量',
    'stat.discount': '平均折扣',
    'stat.buyers': '活跃买家',
    
    // Features
    'features.title': '为什么选择 VentureFlow？',
    'features.description': '一站式字节跳动股权交易服务，从 KYC 认证到交易完成，全程专业支持。',
    'features.kyc.title': 'KYC 认证',
    'features.kyc.desc': '符合香港金融管理局要求的机构级验证流程，确保合规。',
    'features.equity.title': '股权管理',
    'features.equity.desc': '灵感来自 Carta 的股权管理工具，实时追踪投资组合表现。',
    'features.deal.title': '交易执行',
    'features.deal.desc': '专属交易室和香港银行托管账户，确保交易安全。',
    'features.compliance.title': '合规保障',
    'features.compliance.desc': '字节跳动官方授权，法律见证，全面法律保护。',
    
    // Opportunities
    'opp.title': '精选投资机会',
    'opp.description': '经过估值验证的字节跳动股权交易',
    'opp.viewAll': '查看全部',
    'opp.page.title': '投资机会',
    'opp.page.description': '浏览验证公司，探索字节跳动及其他独角兽的独家股权交易机会。',
    'opp.page.sellShares': '💼 出售股份',
    'opp.page.totalCompanies': '公司总数',
    'opp.page.activeListings': '活跃挂牌',
    'opp.page.totalValuation': '总估值',
    'opp.page.companyDetail': '公司详情',
    'opp.page.inquireNow': '💰 立即询价',
    'opp.page.noDeals': '暂无可用的交易机会。',
    'opp.page.contactFA': '联系我们的 FA 团队了解更多机会。',
    'opp.page.backToList': '← 返回机会列表',
    'opp.page.shareOpportunity': '📤 分享机会',
    'opp.page.learnMore': '了解更多',
    
    // Testimonials
    'testimonials.title': '投资者信赖',
    'testimonials.description': '超过 500 家机构和家族办公室通过我们的平台完成字节跳动股权配置',
    'testimonials.verified': '已验证投资者',
    
    // CTA
    'cta.title': '开启您的股权投资之旅',
    'cta.description': '无论您在寻找机构大额交易还是员工期权转让，我们的专业团队提供全程支持。',
    'cta.browse': '浏览投资机会',
    'cta.contact': '联系顾问',
    
    // Footer
    'footer.platform': '平台',
    'footer.legal': '法律',
    'footer.contact': '联系',
    'footer.rights': '© 2026 VentureFlow. 版权所有.',
    
    // About Page
    'about.title': '关于 VentureFlow',
    'about.subtitle': '全球首个字节跳动官方授权股权二级市场交易平台',
    'about.mission': '我们的使命',
    'about.missionText1': '为字节跳动股权交易提供透明、合规、高效的平台，连接机构投资者与优质投资机会。',
    'about.missionText2': '我们架起私人公司股东与合格投资者之间的桥梁，确保公平定价、合规监管和无缝交易执行。',
    'about.missionText3': '我们的平台将尖端技术与深厚的行业专业知识相结合，提供最佳的二级市场体验。',
    'about.milestones': '重要里程碑',
    'about.stats.founded': '成立时间',
    'about.stats.team': '团队规模',
    'about.stats.licensed': '持牌地区',
    'about.stats.transactions': '交易额',
    'about.values.title': '我们的价值观',
    'about.values.desc': '指导我们一切行为的原则',
    'about.values.compliance': '合规至上',
    'about.values.transparency': '透明公开',
    'about.values.efficiency': '高效便捷',
    'about.team.title': '领导团队',
    'about.team.desc': '拥有数十年综合经验的行业资深人士',
    'about.partners.title': '可信赖的合作伙伴',
    'about.partners.desc': '与领先机构合作，提供卓越服务',
    'about.cta.title': '加入股权交易的未来',
    'about.cta.desc': '在最受信赖的字节跳动股权平台开始您的投资之旅',
    'about.cta.start': '立即开始',
    
    // Contact Page
    'contact.title': '联系我们',
    'contact.subtitle': '与我们的专家团队取得联系',
    'contact.email': '电子邮箱',
    'contact.hq': '总部',
    'contact.phone': '电话',
    'contact.wechat': '微信',
    'contact.messageTitle': '发送消息',
    'contact.sent': '消息已发送！',
    'contact.sentDesc': '感谢您的联系。我们的团队将在 24 小时内回复。',
    'contact.sendAnother': '再发一条消息',
    'contact.name': '姓名',
    'contact.emailLabel': '邮箱地址',
    'contact.company': '公司',
    'contact.subject': '主题',
    'contact.selectSubject': '请选择主题',
    'contact.subject.investment': '投资咨询',
    'contact.subject.selling': '出售股份',
    'contact.subject.partnership': '合作机会',
    'contact.subject.support': '技术支持',
    'contact.subject.other': '其他',
    'contact.message': '消息内容',
    'contact.send': '发送消息',
    'contact.sending': '发送中...',
    'contact.officeHours': '办公时间',
    'contact.weekdays': '周一至周五',
    'contact.saturday': '周六',
    'contact.sunday': '周日',
    'contact.hours': '上午 9:00 - 下午 6:00 (香港时间)',
    'contact.appointment': '预约',
    'contact.closed': '休息',
    'contact.departments': '部门',
    'contact.faq.title': '常见问题',
    'contact.faq.desc': '常见问题的快速解答',
    
    // KYC Page
    'kyc.title': 'KYC 认证',
    'kyc.subtitle': '完成投资者身份验证，开启投资机会',
    'kyc.step1': '账户类型',
    'kyc.step2': '基本信息',
    'kyc.step3': '身份信息',
    'kyc.step4': '投资资质',
    'kyc.step5': '风险揭示',
    'kyc.individual': '个人投资者',
    'kyc.institutional': '机构投资者',
    'kyc.fullName': '全名',
    'kyc.email': '邮箱',
    'kyc.phone': '电话',
    'kyc.passport': '护照/身份证号码',
    'kyc.investorCert': '合格投资者证明',
    'kyc.riskDisclosure': '风险揭示书',
    'kyc.submit': '提交认证',
    'kyc.success': '认证成功！',
    'kyc.successDesc': '您的 KYC 申请已提交，我们将在 24 小时内审核。',
    
    // Sell Page
    'sell.title': '出售股份',
    'sell.subtitle': '委托出售您的持股，我们的专业团队将为您提供最佳定价方案',
    'sell.step1': '资产信息',
    'sell.step2': '卖家信息',
    'sell.step3': '文件上传',
    'sell.step4': '补充信息',
    'sell.companyName': '公司名称',
    'sell.shareType': '股份类型',
    'sell.shareCount': '股份数量',
    'sell.estimatedValue': '预估价值',
    'sell.sellerType': '卖家类型',
    'sell.contactName': '联系人',
    'sell.documents': '文件上传',
    'sell.proofOfOwnership': '持股证明',
    'sell.purchaseAgreement': '购买协议',
    'sell.idVerification': '身份证明',
    'sell.reasonForSelling': '出售原因',
    'sell.minimumPrice': '最低价格',
    'sell.urgency': '紧急程度',
    'sell.submit': '提交委托',
    'sell.success': '委托已提交！',
    'sell.successDesc': '我们的 FA 团队将在 2 小时内与您联系，提供市场估值和交易建议。',
    
    // Company Detail Page
    'company.detail': '公司详情',
    'company.inquireNow': '💰 立即询价',
    'company.noDeals': '暂无可用的交易机会。',
    'company.contactFA': '联系我们的 FA 团队了解更多机会。',
    'company.backToList': '← 返回机会列表',
    'company.shareOpportunity': '📤 分享机会',
    'company.learnMore': '了解更多',
    'company.valuation': '估值',
    'company.pricePerShare': '每股价格',
    'company.volume': '交易量',
    'company.discount': '折扣',
    'company.founded': '成立时间',
    'company.headquarters': '总部',
    'company.industry': '行业',
    'company.description': '公司简介',
    'company.activeDeals': '活跃交易',
    'company.expressInterest': 'Express Interest',
    
    // Login Pages
    'login.title': 'FA 后台管理',
    'login.email': '邮箱',
    'login.password': '密码',
    'login.signIn': '登录',
    'login.signingIn': '登录中...',
    'login.demoCredentials': '演示账号：',
    'login.investorLink': '👤 投资者登录 →',
    
    'userLogin.title': '投资者登录',
    'userLogin.subtitle': '访问您的投资组合和机会',
    'userLogin.emailLabel': '邮箱地址',
    'userLogin.passwordLabel': '密码',
    'userLogin.signIn': '登录',
    'userLogin.signingIn': '登录中...',
    'userLogin.kycLink': '完成 KYC 认证注册',
    'userLogin.faLoginLink': 'FA/管理员登录 →',
    'userLogin.demoNote': '演示模式：任意邮箱/密码',
    
    // FA Dashboard
    'faDash.title': '仪表板',
    'faDash.totalGmv': '总交易额',
    'faDash.pendingBuyers': '待审核买家',
    'faDash.activeDeals': '进行中交易',
    'faDash.monthlyClosed': '本月完成',
    'faDash.recentActivity': '最近活动',
    'faDash.quickActions': '快捷操作',
    'faDash.marketOverview': '市场概览',
    'faDash.reviewKYC': '审核 KYC',
    'faDash.createAsset': '创建资产',
    'faDash.manageDeals': '管理交易',
    'faDash.aiTools': 'AI 工具',
    
    // Buyers Page
    'buyers.title': '买家管理',
    'buyers.search': '搜索买家...',
    'buyers.addBuyer': '添加买家',
    'buyers.buyer': '买家',
    'buyers.email': '邮箱',
    'buyers.type': '类型',
    'buyers.kycStatus': 'KYC 状态',
    'buyers.inquiries': '询盘',
    'buyers.lastContact': '最后联系',
    'buyers.actions': '操作',
    'buyers.viewDetails': '查看详情',
    'buyers.approveKYC': '批准 KYC',
    'buyers.rejectKYC': '拒绝 KYC',
    'buyers.addFollowUp': '添加跟进',
    'buyers.sendEmail': '发送邮件',
    'buyers.scheduleMeeting': '安排会议',
    'buyers.aiGenerate': '✨ AI 生成',
    
    // Orders Page
    'orders.title': '订单管理',
    'orders.createOrder': '创建订单',
    'orders.orderId': '订单号',
    'orders.asset': '资产',
    'orders.buyer': '买家',
    'orders.amount': '金额',
    'orders.status': '状态',
    'orders.created': '创建时间',
    'orders.view': '查看',
    'orders.updateStatus': '更新状态',
    
    // Assets Page
    'assets.title': '资产管理',
    'assets.createAsset': '创建资产',
    'assets.assetName': '资产名称',
    'assets.valuation': '估值',
    'assets.priceShare': '每股价格',
    'assets.volume': '交易量',
    'assets.discount': '折扣',
    'assets.status': '状态',
    'assets.edit': '编辑',
    'assets.deactivate': '下架',
    
    // Deals Page
    'deals.title': '交易管道',
    'deals.newDeal': '新交易',
    'deals.dealName': '交易名称',
    'deals.value': '金额',
    'deals.stage': '阶段',
    'deals.lead': '负责人',
    'deals.probability': '成功率',
    'deals.moveForward': '推进',
    'deals.moveBack': '后退',
    
    // Agreements Page
    'agreements.title': '协议管理',
    'agreements.newAgreement': '新协议',
    'agreements.agreementName': '协议名称',
    'agreements.type': '类型',
    'agreements.party': '签约方',
    'agreements.status': '状态',
    'agreements.signed': '已签署',
    'agreements.pending': '待签署',
    'agreements.draft': '草稿',
    'agreements.download': '下载',
    'agreements.send': '发送',
    
    // Commission Page
    'commission.title': '佣金追踪',
    'commission.dealId': '交易编号',
    'commission.amount': '交易金额',
    'commission.rate': '佣金比例',
    'commission.commission': '佣金',
    'commission.dueDate': '到期日',
    'commission.export': '导出报表',
    
    // AI Tools Page
    'aiTools.title': 'AI 分析中心',
    'aiTools.emailGen': '邮件生成器',
    'aiTools.buyerAnalysis': '买家分析',
    'aiTools.smartMatch': '智能匹配',
    'aiTools.scheduleAssistant': '日程助手',
    'aiTools.generateEmail': '生成邮件',
    'aiTools.analyzeBuyer': '分析买家',
    'aiTools.findMatches': '查找匹配',
    'aiTools.scheduleMeeting': '安排会议',
    
    // Settings Page
    'settings.title': '设置',
    'settings.profile': '个人设置',
    'settings.notifications': '通知设置',
    'settings.team': '团队管理',
    'settings.apiKeys': 'API 密钥',
    'settings.save': '保存更改',
    'settings.logout': '退出登录',
    
    // User Dashboard
    'userDash.title': '我的投资组合',
    'userDash.totalValue': '总投资组合价值',
    'userDash.totalGainLoss': '总盈亏',
    'userDash.activeInquiries': '进行中询盘',
    'userDash.myHoldings': '我的持股',
    'userDash.shares': '股',
    'userDash.avgPrice': '平均成本',
    'userDash.currentPrice': '当前价格',
    'userDash.refValuation': '参考估值',
    'userDash.requestSell': '申请出售',
    'userDash.details': '详情',
    'userDash.myInquiries': '我的询盘',
    'userDash.newInquiry': '+ 新询盘',
    'userDash.quickActions': '快捷操作',
    'userDash.browseOpp': '浏览投资机会',
    'userDash.sellShares': '出售我的股份',
    'userDash.sellRequestTitle': '申请出售',
    'userDash.sharesCount': '股份数量',
    'userDash.estValue': '预估价值',
    'userDash.faContact': 'FA 代表将在 24 小时内与您联系。',
    'userDash.cancel': '取消',
    'userDash.submitRequest': '提交申请',
  },
};

const LangContext = createContext<LangContextType | undefined>(undefined);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');

  const t = (key: string): string => {
    return translations[lang][key as keyof typeof translations.en] || key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LangContext);
  if (context === undefined) {
    throw new Error('useLang must be used within a LangProvider');
  }
  return context;
}
